---

- name: restart named
  ansible.builtin.systemd:
    name: named.service
    state: restarted
    enabled: yes


- name: restart httpd
  ansible.builtin.systemd:
    name: httpd.service
    state: restarted
    enabled: yes
