

- name: Install needed package iSCSI target
  yum:
    name: targetcli
    state: latest

- name: Check iSCSI target
  shell: /usr/bin/targetcli /backstores/fileio ls
  register: disk
  changed_when: false
  ignore_errors: yes

- block:
    - name: Create iSCSI
      shell: /usr/bin/targetcli /backstores/fileio/ create disk01 /disk01.img 1G
    - shell: /usr/bin/targetcli /iscsi create iqn.2018-03.com.example:target01
    - shell: /usr/bin/targetcli /iscsi/iqn.2018-03.com.example:target01/tpg1/luns create /backstores/fileio/disk01
    - shell: /usr/bin/targetcli /iscsi/iqn.2018-03.com.example:target01/tpg1/acls create iqn.2018-03.com.example:client
  when: disk.stdout.find('write-back activated') == -1

- name: Enable and start iSCSI target service
  systemd:
    name: target.service
    enabled: true
    state: started


- name: Add sample index.html folder
  file:
    path: /var/www/html/files
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: Add sample index.html
  copy:
    src: files/server/index.html
    dest: /var/www/html/files
    owner: apache
    group: apache
    mode: 0644


- name: Configure Firewalld
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - ldap
    - ldaps
    - http
    - https
    - ntp
    - samba
    - nfs
    - rpc-bind
    - mountd
    - iscsi-target


- name: Create repo metadata
  command: /usr/bin/createrepo /var/www/html/repos/
  args:
    creates: /var/www/html/repos/repodata/


- name: Install needed packages for IPA Server
  yum:
    name: ipa-server
    state: latest

- name: Update /etc/hosts with server ip. Required for the IPA Server
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"


- block:
    - name: Install IPA Server
      shell: /usr/sbin/ipa-server-install --unattended --admin-password=ex200server --ds-password=ex200server --domain=example.com --realm=EXAMPLE.COM
      args:
        creates: /run/dirsrv/slapd-EXAMPLE-COM.pid

  rescue:
    - name: Uninstalling IPA server...
      shell: /usr/sbin/ipa-server-install --unattended  --uninstall
    - fail:
        msg: "Errors installing IPA Server. Will uninstall. Check the logs and try again."

